"use client";

import { useState, useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { AlertTriangle } from "lucide-react";
import type { TemplateField } from "@/lib/types";

const FIELD_TYPES = [
  { value: "text", label: "Texto" },
  { value: "textarea", label: "Texto largo" },
  { value: "boolean", label: "Sí/No" },
  { value: "number", label: "Número" },
  { value: "date", label: "Fecha" },
  { value: "select", label: "Selección" },
  { value: "multiselect", label: "Selección múltiple" },
] as const;

type FieldType = TemplateField["type"];

function labelToKey(label: string): string {
  return label
    .replace(/[¿?¡!]/g, "")
    .split(/[\s-_]+/)
    .map((word, i) =>
      i === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
    )
    .join("");
}

interface FieldFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  field?: TemplateField | null;
  existingKeys: string[];
  onSave: (field: Omit<TemplateField, "sortOrder">) => void;
}

export function FieldFormDialog({
  open,
  onOpenChange,
  field,
  existingKeys,
  onSave,
}: FieldFormDialogProps) {
  const isEditing = !!field;
  const isSystem = field?.system ?? false;

  const [label, setLabel] = useState("");
  const [key, setKey] = useState("");
  const [type, setType] = useState<FieldType>("text");
  const [optionsText, setOptionsText] = useState("");
  const [required, setRequired] = useState(false);
  const [isActive, setIsActive] = useState(true);
  const [originalType, setOriginalType] = useState<FieldType | null>(null);
  const [keyError, setKeyError] = useState("");
  const [wasAutoGenerated, setWasAutoGenerated] = useState(true);

  // Reset state when dialog opens/closes
  useEffect(() => {
    if (open) {
      if (field) {
        setLabel(field.label);
        setKey(field.key);
        setType(field.type);
        setOptionsText(field.options?.join("\n") ?? "");
        setRequired(field.required ?? false);
        setIsActive(field.isActive ?? true);
        setOriginalType(field.type);
        setWasAutoGenerated(false);
      } else {
        setLabel("");
        setKey("");
        setType("text");
        setOptionsText("");
        setRequired(false);
        setIsActive(true);
        setOriginalType(null);
        setWasAutoGenerated(true);
      }
      setKeyError("");
    }
  }, [open, field]);

  const handleLabelChange = (value: string) => {
    setLabel(value);
    if (!isEditing && wasAutoGenerated) {
      setKey(labelToKey(value));
    } else if (isEditing && wasAutoGenerated && !isSystem) {
      setKey(labelToKey(value));
    }
  };

  const handleKeyChange = (value: string) => {
    setKey(value);
    setWasAutoGenerated(false);
    setKeyError("");
  };

  const handleSave = () => {
    if (!label.trim()) return;

    // Validate key uniqueness
    const finalKey = key || labelToKey(label);
    const keysToCheck = existingKeys.filter(
      (k) => k !== (field?.key ?? ""),
    );
    if (keysToCheck.includes(finalKey)) {
      setKeyError("Ya existe un campo con esta clave");
      return;
    }

    const options = type === "select" || type === "multiselect"
      ? optionsText
          .split("\n")
          .map((l) => l.trim())
          .filter(Boolean)
      : undefined;

    onSave({
      key: finalKey,
      label: label.trim(),
      type,
      options: options?.length ? options : undefined,
      required,
      isActive,
      system: field?.system,
    });
    onOpenChange(false);
  };

  const showOptions = type === "select" || type === "multiselect";
  const typeChanged = isEditing && originalType && originalType !== type;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>
            {isEditing ? "Editar campo" : "Agregar campo"}
          </DialogTitle>
          <DialogDescription>
            Completá los datos del campo de exploración
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Label */}
          <div className="space-y-2">
            <Label htmlFor="field-label">
              Label <span className="text-destructive">*</span>
            </Label>
            <Input
              id="field-label"
              value={label}
              onChange={(e) => handleLabelChange(e.target.value)}
              placeholder="Ej: Tipo de piel"
            />
          </div>

          {/* Key */}
          <div className="space-y-2">
            <Label htmlFor="field-key">Key</Label>
            <Input
              id="field-key"
              value={key}
              onChange={(e) => handleKeyChange(e.target.value)}
              placeholder="Se genera automáticamente"
              disabled={isSystem}
              className={isSystem ? "opacity-50" : ""}
            />
            {keyError && (
              <p className="text-destructive text-sm">{keyError}</p>
            )}
            {isSystem && (
              <p className="text-muted-foreground text-xs">
                Campo del sistema — key no editable
              </p>
            )}
          </div>

          {/* Type */}
          <div className="space-y-2">
            <Label htmlFor="field-type">
              Tipo <span className="text-destructive">*</span>
            </Label>
            <Select
              value={type}
              onValueChange={(v) => setType(v as FieldType)}
            >
              <SelectTrigger className="w-full" id="field-type">
                <SelectValue placeholder="Seleccionar tipo..." />
              </SelectTrigger>
              <SelectContent>
                {FIELD_TYPES.map((ft) => (
                  <SelectItem key={ft.value} value={ft.value}>
                    {ft.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {typeChanged && (
              <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
                <AlertTriangle className="mt-0.5 size-4 shrink-0" />
                <p>
                  Modificar el tipo de un campo puede afectar la visualización
                  de respuestas históricas.
                </p>
              </div>
            )}
          </div>

          {/* Options (select/multiselect only) */}
          {showOptions && (
            <div className="space-y-2">
              <Label htmlFor="field-options">Opciones</Label>
              <Textarea
                id="field-options"
                value={optionsText}
                onChange={(e) => setOptionsText(e.target.value)}
                placeholder="Una opción por línea"
                rows={4}
              />
              <p className="text-muted-foreground text-xs">
                Ingresá una opción por línea
              </p>
            </div>
          )}

          {/* Switches row */}
          <div className="flex items-center justify-between">
            <Label htmlFor="field-required">Requerido</Label>
            <Switch
              id="field-required"
              checked={required}
              onCheckedChange={setRequired}
            />
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="field-active">Activo</Label>
            <Switch
              id="field-active"
              checked={isActive}
              onCheckedChange={setIsActive}
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancelar
          </Button>
          <Button onClick={handleSave} disabled={!label.trim()}>
            Guardar
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
